--- #YAML:1.0
name:               Authen-UserVerify
version:            0.07
abstract:           Generate and verify unique codes to be used to
author:
    - Terence Monteiro
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Random:  0.05
    Digest::SHA1:  2.11
    File::Copy:    2.09
    File::Temp:    0.18
    Text::CSV_XS:  0.26
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
